export const COUNTER_CONST={INCREMENT:"INCREMENT",DECREMENT:"DECREMENT", SIGN_IN:"SIGN_IN",  GET_POST:"GET_POST"}

export const USERS_CONST={GET_USERS_REQUEST:"GET_USERS_REQUEST", GET_USERS_FAILURE:"GET_USERS_FAILURE", GET_USERS_SUCCESS:"GET_USERS_SUCCESS"

}


export const POSTS_CONST={GET_POSTS_REQUEST:"GET_POSTS_REQUEST", GET_POSTS_FAILURE:"GET_POSTS_FAILURE", GET_POSTS_SUCCESS:"GET_POSTS_SUCCESS"}