export const COUNTER_CONST={INCREMENT:"INCREMENT",DECREMENT:"DECREMENT", SIGN_IN:"SIGN_IN"}

export const USERS_CONST={GET_USERS_REQUEST:"GET_USERS_REQUEST", GET_ALL_USERS:"GET_ALL_USERS"}


export const ADD_USERS_CONST={ADD_USERS_REQUEST:"ADD_USERS_REQUEST", ADD_USERS_SUCCESS:"ADD_USERS_SUCCESS"}